[project]
name = "hass-template-climate-ir-tuya-UC"
version = "0.0.1"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorlog>=6.9.0",
    "homeassistant>=2024.11.2",
]
